application: salarymap-1122
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /static
  static_dir: static/

- url: /js
  static_dir: static/js

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

